# Generated by Django 3.1.4 on 2021-01-01 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210101_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='effective_from_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='address',
            name='effective_to_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_one',
            field=models.CharField(max_length=100, verbose_name='Address Line One'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_three',
            field=models.CharField(max_length=100, null=True, verbose_name='Address Line Three'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_two',
            field=models.CharField(max_length=100, null=True, verbose_name='Address Line Two'),
        ),
        migrations.AlterField(
            model_name='address',
            name='town',
            field=models.CharField(max_length=100, verbose_name='Town/City'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_inserted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
