# Generated by Django 3.1.4 on 2021-01-01 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210101_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': "Address's"},
        ),
        migrations.AlterModelOptions(
            name='contactdetails',
            options={'verbose_name': 'Contact Details', 'verbose_name_plural': 'Contact Details'},
        ),
    ]
