# Generated by Django 3.1.4 on 2021-01-01 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210101_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address Details', 'verbose_name_plural': 'Address Details'},
        ),
    ]
