# Generated by Django 3.1.4 on 2021-01-02 13:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210101_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('effective_from_date', models.DateField(default=django.utils.timezone.now)),
                ('effective_to_date', models.DateField(null=True)),
                ('date_inserted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only letters are allowed.')])),
                ('surname', models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only letters are allowed.')])),
                ('date_of_birth', models.DateField(null=True)),
                ('school_year', models.CharField(choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('5', 'Year 5'), ('6', 'Year 6'), ('7', 'Year 7'), ('8', 'Year 8'), ('9', 'Year 9'), ('10', 'Year 10'), ('11', 'Year 11'), ('0', 'No longer in school')], default=1, max_length=2)),
                ('date_inserted', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ManyToManyField(to='accounts.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=100)),
                ('term_start_date', models.DateField()),
                ('term_end_date', models.DateField()),
                ('half_term_start_date', models.DateField()),
                ('half_term_end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TuitionAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_one', models.CharField(max_length=100, verbose_name='Address Line One')),
                ('line_two', models.CharField(max_length=100, null=True, verbose_name='Address Line Two')),
                ('line_three', models.CharField(max_length=100, null=True, verbose_name='Address Line Three')),
                ('town', models.CharField(max_length=100, verbose_name='Town/City')),
                ('postcode', models.CharField(max_length=10)),
                ('effective_from_date', models.DateField(default=django.utils.timezone.now)),
                ('effective_to_date', models.DateField(null=True)),
                ('date_inserted', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'verbose_name': 'Student Address',
                'verbose_name_plural': 'Student Address',
            },
        ),
    ]
