# Generated by Django 3.1.4 on 2021-01-02 13:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_products_student_term_tuitionaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='effective_to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_three',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line Three'),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_two',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line Two'),
        ),
        migrations.AlterField(
            model_name='products',
            name='effective_to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='tuitionaddress',
            name='effective_to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tuitionaddress',
            name='line_three',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line Three'),
        ),
        migrations.AlterField(
            model_name='tuitionaddress',
            name='line_two',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address Line Two'),
        ),
    ]
