# Generated by Django 3.1.4 on 2021-01-03 23:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210102_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('status', models.PositiveSmallIntegerField(choices=[('1', 'Draft'), ('2', 'Issued'), ('3', 'Unpaid'), ('4', 'Part paid'), ('5', 'Paid')], default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_outstanding', models.DecimalField(decimal_places=2, max_digits=8)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.client')),
            ],
        ),
        migrations.AlterField(
            model_name='tuitionaddress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_student', to='accounts.student'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_start', models.DateTimeField()),
                ('lesson_end', models.DateTimeField()),
                ('invoiced', models.BooleanField(default=False)),
                ('invoice_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term', to='accounts.invoices')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_type', to='accounts.products')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_student', to='accounts.student')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term', to='accounts.term')),
            ],
        ),
    ]
