# Generated by Django 3.1.4 on 2021-01-13 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210103_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_link', to='accounts.products'),
        ),
    ]
