# Generated by Django 3.1.4 on 2021-01-13 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210113_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
