# Generated by Django 3.1.4 on 2021-01-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210113_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.CharField(choices=[(1, 'Draft'), (2, 'Issued'), (3, 'Unpaid'), (4, 'Part paid'), (5, 'Paid')], default=1, max_length=2),
        ),
    ]
