# Generated by Django 3.1.4 on 2021-01-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20210113_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_year',
            field=models.CharField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5'), (6, 'Year 6'), (7, 'Year 7'), (8, 'Year 8'), (9, 'Year 9'), (10, 'Year 10'), (11, 'Year 11'), (0, 'No longer in school')], default=1, max_length=2),
        ),
    ]
