# Generated by Django 3.1.4 on 2021-01-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20210113_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Issued'), (3, 'Unpaid'), (4, 'Part paid'), (5, 'Paid')], default=1),
        ),
    ]
