# Generated by Django 3.1.4 on 2021-01-14 10:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210113_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.client'),
        ),
        migrations.AlterField(
            model_name='contactdetails',
            name='email_address',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
