# Generated by Django 3.1.4 on 2021-01-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210114_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.client'),
        ),
    ]
